<template>
  <div>
    <el-collapse-transition>
      <div id="zsd" :class="{ movezsd: zsdTransition }">
        <div class="arrow" @click="zsdTranslate = !zsdTranslate"><p>知<br/>识<br/>点</p></div>
        <div class="tree">
          <el-input
            placeholder="搜索知识点"
            v-model="zsdText">
          </el-input>
          <el-tree
            class="zsd-tree"
            :data="zsdTree"
            :props="defaultProps"
            :filter-node-method="filterNode"
            @node-click="handleNodeClick"
            ref="zsdTree">
          </el-tree>
        </div>
      </div>
    </el-collapse-transition>
  </div>
</template>

<script>
  export default {
    data () {
      return {
        nowValue: this.$store.state.value,
        zsdTranslate: true,
        zsdText: '',
        zsdTree: [{
          label: '数与式',
          children: [{
            label: '有理数',
            children: [{
              label: '正数和负数'
            }, {
              label: '有理数'
            }, {
              label: '数轴'
            }, {
              label: '相反数'
            }, {
              label: '绝对值'
            }, {
              label: '非负数的性质：绝对值'
            }, {
              label: '倒数'
            }, {
              label: '有理数的大小比较'
            }, {
              label: '有理数的加法'
            }, {
              label: '有理数的减法'
            }, {
              label: '有理数的加减混合运算'
            }, {
              label: '有理数的乘法'
            }, {
              label: '有理数的除法'
            }, {
              label: '非负数的性质：偶次方'
            }, {
              label: '有理数的混合运算'
            }, {
              label: '近似数和有效数字'
            }, {
              label: '科学记数法—表示较大的数'
            }, {
              label: '科学记数法—表示较小的数'
            }, {
              label: '科学记数法—原数'
            }, {
              label: '科学记数法与有效数字'
            }, {
              label: '计算器—基础知识'
            }, {
              label: '计算器—有理数'
            }, {
              label: '数学常识'
            }, {
              label: '用数字表示事件'
            }, {
              label: '尾数特征'
            }]
          }, {
            label: '无理数与实数',
            children: [{
              label: '平方根'
            }, {
              label: '算术平方根'
            }, {
              label: '非负数的性质：算术平方根'
            }, {
              label: '立方根'
            }, {
              label: '计算器—数的开方'
            }, {
              label: '无理数'
            }, {
              label: '实数'
            }, {
              label: '实数的性质'
            }, {
              label: '实数与数轴'
            }, {
              label: '实数大小比较'
            }, {
              label: '估算无理数的大小'
            }, {
              label: '实数的运算'
            }, {
              label: '分数指数幂'
            }]
          }, {
            label: '代数式',
            children: [{
              label: '代数式'
            }, {
              label: '列代数式'
            }, {
              label: '代数式求值'
            }, {
              label: '同类项'
            }, {
              label: '合并同类项'
            }, {
              label: '去括号和添括号'
            }, {
              label: '规律型：数字的变化类'
            }, {
              label: '规律性：图形的变化类'
            }]
          }, {
            label: '整式',
            children: [{
              label: '整式'
            }, {
              label: '单项式'
            }, {
              label: '多项式'
            }, {
              label: '整式的加减'
            }, {
              label: '整式的加减—化简求值'
            }, {
              label: '同底数幂的乘法'
            }, {
              label: '幂的乘方和积的乘方'
            }, {
              label: '同底数幂的除法'
            }, {
              label: '单项式乘单项式'
            }, {
              label: '单项式乘多项式'
            }, {
              label: '多项式乘多项式'
            }, {
              label: '完全平方公式'
            }, {
              label: '完全平方公式的几何背景'
            }, {
              label: '完全平方式'
            }, {
              label: '平方差公式'
            }, {
              label: '平方差公式的几何背景'
            }, {
              label: '整式的除法'
            }, {
              label: '整式的混合运算'
            }, {
              label: '整式的混合运算—化简求值'
            }]
          }, {
            label: '因式分解',
            children: [{
              label: '因式分解的意义'
            }, {
              label: '公因式'
            }, {
              label: '因式分解-提公因式法'
            }, {
              label: '因式分解-运用公式法'
            }, {
              label: '提公因式法和运用公式法的综合运用'
            }, {
              label: '因式分解-分组分解法'
            }, {
              label: '因式分解-十字相乘法'
            }, {
              label: '实数范围内分解因式'
            }, {
              label: '因式分解的应用'
            }]
          }, {
            label: '分式',
            children: [{
              label: '分式的意义'
            }, {
              label: '分式有意义的条件'
            }, {
              label: '分式的值为零的条件'
            }, {
              label: '分式的值'
            }, {
              label: '分式的基本性质'
            }, {
              label: '约分'
            }, {
              label: '通分'
            }, {
              label: '最简分式'
            }, {
              label: '最简公分母'
            }, {
              label: '分式的乘除法'
            }, {
              label: '分式的加减法'
            }, {
              label: '分式的混合运算'
            }, {
              label: '分式的化简求值'
            }, {
              label: '零指数幂'
            }, {
              label: '负整数指数幂'
            }, {
              label: '列代数式（分式）'
            }]
          }, {
            label: '二次根式',
            children: [{
              label: '二次根式的定义'
            }, {
              label: '二次根式有意义的条件'
            }, {
              label: '二次根式的性质与化简'
            }, {
              label: '最简二次根式'
            }, {
              label: '二次根式的乘除法'
            }, {
              label: '分母有理化'
            }, {
              label: '同类二次根式'
            }, {
              label: '二次根式的加减法'
            }, {
              label: '二次根式的混合运算'
            }, {
              label: '二次根式的化简求值'
            }, {
              label: '二次根式的应用'
            }]
          }]
        }, {
          label: '方程与不等式',
          children: [{
            label: '一元一次方程',
            children: [{
              label: '方程的定义'
            }, {
              label: '方程的解'
            }, {
              label: '等式的性质'
            }, {
              label: '一元一次方程的定义'
            }, {
              label: '一元一次方程的解'
            }, {
              label: '解一元一次方程'
            }, {
              label: '含绝对值符号的一元一次方程'
            }, {
              label: '同解方程'
            }, {
              label: '实际问题抽象出一元一次方程'
            }, {
              label: '一元一次方程的应用'
            }]
          }, {
            label: '二元一次方程组',
            children: [{
              label: '二元一次方程的定义'
            }, {
              label: '二元一次方程的解'
            }, {
              label: '解二元一次方程'
            }, {
              label: '实际问题抽象出二元一次方程'
            }, {
              label: '二元一次方程的应用'
            }, {
              label: '二元一次方程组的定义'
            }, {
              label: '二元一次方程组的解'
            }, {
              label: '解二元一次方程组'
            }, {
              label: '实际问题抽象出二元一次方程组'
            }, {
              label: '二元一次方程组的应用'
            }, {
              label: '同解方程组'
            }, {
              label: '解三元一次方程组'
            }, {
              label: '三元一次方程组的应用'
            }]
          }, {
            label: '一元二次方程',
            children: [{
              label: '一元二次方程的定义'
            }, {
              label: '一元二次方程的一般形式'
            }, {
              label: '一元二次方程的解'
            }, {
              label: '估算一元二次方程的近似解'
            }, {
              label: '解一元二次方程-直接开方法'
            }, {
              label: '解一元二次方程-配方法'
            }, {
              label: '解一元二次方程-公式法'
            }, {
              label: '解一元二次方程-因式分解法'
            }, {
              label: '换元法解一元二次方程'
            }, {
              label: '根的判别式'
            }, {
              label: '根与系数的关系'
            }, {
              label: '实际问题抽象出一元二次方程'
            }, {
              label: '一元二次方程的应用'
            }, {
              label: '配方法的应用'
            }, {
              label: '高次方程'
            }, {
              label: '无理方程'
            }]
          }, {
            label: '分式方程',
            children: [{
              label: '分式方程的定义'
            }, {
              label: '分式方程的解'
            }, {
              label: '解分式方程'
            }, {
              label: '换元法解分式方程'
            }, {
              label: '分式方程的增根'
            }, {
              label: '实际问题抽象出分式方程'
            }, {
              label: '分式方程的应用'
            }]
          }, {
            label: '不等式与不等式组',
            children: [{
              label: '不等式的定义'
            }, {
              label: '不等式的性质'
            }, {
              label: '不等式的解集'
            }, {
              label: '在数轴上表示不等式的解集'
            }, {
              label: '一元一次不等式的定义'
            }, {
              label: '解一元一次不等式'
            }, {
              label: '一元一次不等式的整数解'
            }, {
              label: '实际问题抽象出一元一次不等式'
            }, {
              label: '一元一次不等式的应用'
            }, {
              label: '一元一次不等式组的定义'
            }, {
              label: '解一元一次不等式组'
            }, {
              label: '一元一次不等式组的整数解'
            }, {
              label: '实际问题抽象出一元一次不等式组'
            }, {
              label: '一元一次不等式组的应用'
            }]
          }]
        }, {
          label: '函数',
          children: [{
            label: '平面直角坐标系',
            children: [{
              label: '点的坐标'
            }, {
              label: '规律型：点的坐标'
            }, {
              label: '坐标确定位置'
            }, {
              label: '坐标与图形性质'
            }, {
              label: '两点间的距离公式'
            }]
          }, {
            label: '函数基础知识',
            children: [{
              label: '常量与变量'
            }, {
              label: '函数的概念'
            }, {
              label: '函数关系式'
            }, {
              label: '函数自变量的取值范围'
            }, {
              label: '函数值'
            }, {
              label: '函数的图像'
            }, {
              label: '动点问题的函数图像'
            }, {
              label: '函数的表示方法'
            }, {
              label: '分段函数'
            }]
          }, {
            label: '一次函数',
            children: [{
              label: '一次函数的定义'
            }, {
              label: '正比例函数的定义'
            }, {
              label: '一次函数的图像'
            }, {
              label: '正比例函数的图像'
            }, {
              label: '一次函数的性质'
            }, {
              label: '正比例函数的性质'
            }, {
              label: '一次函数的图像与系数的关系'
            }, {
              label: '一次函数图像上点的坐标特征'
            }, {
              label: '一次函数图像与几何变换'
            }, {
              label: '待定系数法求一次函数解析式'
            }, {
              label: '待定系数法求正比例函数解析式'
            }, {
              label: '一次函数与一元一次方程'
            }, {
              label: '一次函数与一元一次不等式'
            }, {
              label: '一次函数与二元一次方程（组）'
            }, {
              label: '两条直线相交或平行问题'
            }, {
              label: '根据实际问题列一次函数关系式'
            }, {
              label: '一次函数的应用'
            }, {
              label: '一次函数综合题'
            }]
          }, {
            label: '反比例函数',
            children: [{
              label: '反比例函数的定义'
            }, {
              label: '反比例函数的图像'
            }, {
              label: '反比例函数图像的对称性'
            }, {
              label: '反比例函数的性质'
            }, {
              label: '反比例函数系数K的几何意义'
            }, {
              label: '待定系数法求反比例函数解析式'
            }, {
              label: '反比例函数图像上点的坐标特征'
            }, {
              label: '反比例函数与一次函数的交点问题'
            }, {
              label: '根据实际问题列反比例函数关系式'
            }, {
              label: '反比例函数的应用'
            }, {
              label: '反比例函数的综合题'
            }]
          }, {
            label: '二次函数',
            children: [{
              label: '二次函数的定义'
            }, {
              label: '二次函数的图像'
            }, {
              label: '二次函数的性质'
            }, {
              label: '二次函数图像与系数的关系'
            }, {
              label: '二次函数图像上点的坐标特征'
            }, {
              label: '二次函数图像与几何变换'
            }, {
              label: '二次函数的最值'
            }, {
              label: '待定系数法求二次函数解析式'
            }, {
              label: '二次函数的三种形式'
            }, {
              label: '抛物线与x轴的交点'
            }, {
              label: '图像法求一元二次方程的近似根'
            }, {
              label: '二次函数与不等式（组）'
            }, {
              label: '根据实际问题列二次函数关系式'
            }, {
              label: '二次函数的应用'
            }, {
              label: '二次函数综合题'
            }]
          }]
        }, {
          label: '图形的性质',
          children: [{
            label: '图形初步认识',
            children: [{
              label: '认识立体图形'
            }, {
              label: '点、线、面、体'
            }, {
              label: '欧拉公式'
            }, {
              label: '几何体的表面积'
            }, {
              label: '认识平面图形'
            }, {
              label: '几何体的展开图'
            }, {
              label: '展开图折叠成几何体'
            }, {
              label: '专题：正方体相对两个面上的文字'
            }, {
              label: '截一个几何体'
            }, {
              label: '直线、射线、线段'
            }, {
              label: '直线的性质：两点确定一条直线'
            }, {
              label: '线段的性质：两点之间线段最短'
            }, {
              label: '两点间的距离'
            }, {
              label: '比较线段的长短'
            }, {
              label: '角的概念'
            }, {
              label: '钟面角'
            }, {
              label: '方向角'
            }, {
              label: '度分秒的换算'
            }, {
              label: '角平分线的定义'
            }, {
              label: '角的计算'
            }, {
              label: '余角和补角'
            }, {
              label: '七巧板'
            }, {
              label: '线段的和差'
            }, {
              label: '角的大小比较'
            }, {
              label: '计算器-角的换算'
            }]
          }, {
            label: '相交线与平行线',
            children: [{
              label: '相交线'
            }, {
              label: '对顶角、邻补角'
            }, {
              label: '垂线'
            }, {
              label: '垂线段最短'
            }, {
              label: '点到直线的距离'
            }, {
              label: '同位角、内错角、同旁内角'
            }, {
              label: '平行线'
            }, {
              label: '平行公理及推论'
            }, {
              label: '平行线的判定'
            }, {
              label: '平行线的性质'
            }, {
              label: '平行线的判定与性质'
            }, {
              label: '平行线之间的距离'
            }]
          }, {
            label: '三角形',
            children: [{
              label: '三角形'
            }, {
              label: '三角形的角平分线、中线和高'
            }, {
              label: '三角形的面积'
            }, {
              label: '三角形的稳定性'
            }, {
              label: '三角形的重心'
            }, {
              label: '三角形的三边关系'
            }, {
              label: '三角形内角和定理'
            }, {
              label: '三角形的外角性质'
            }, {
              label: '全等图形'
            }, {
              label: '全等三角形的性质'
            }, {
              label: '全等三角形的判定'
            }, {
              label: '直角三角形全等的判定'
            }, {
              label: '全等三角形的判定与性质'
            }, {
              label: '全等三角形的应用'
            }, {
              label: '角平分线的性质'
            }, {
              label: '线段垂直平分线的性质'
            }, {
              label: '等腰三角形的性质'
            }, {
              label: '等腰三角形的判定'
            }, {
              label: '等腰三角形的判定与性质'
            }, {
              label: '等边三角形的性质'
            }, {
              label: '等边三角形的判定'
            }, {
              label: '等边三角形的判定和性质'
            }, {
              label: '直角三角形的性质'
            }, {
              label: '含30度角的直角三角形'
            }, {
              label: '直角三角形斜边上的中线'
            }, {
              label: '勾股定理'
            }, {
              label: '勾股定理的证明'
            }, {
              label: '勾股定理的逆定理'
            }, {
              label: '勾股数'
            }, {
              label: '勾股定理的应用'
            }, {
              label: '平面展开-最短路径问题'
            }, {
              label: '等腰直角三角形'
            }, {
              label: '三角形中位线定理'
            }, {
              label: '三角形综合题'
            }]
          }, {
            label: '四边形',
            children: [{
              label: '多边形'
            }, {
              label: '多边形的对角线'
            }, {
              label: '多边形内角与外角'
            }, {
              label: '平面镶嵌（密铺）'
            }, {
              label: '平行四边形的性质'
            }, {
              label: '平行四边形的判定'
            }, {
              label: '平行四边形的判定与性质'
            }, {
              label: '菱形的性质'
            }, {
              label: '菱形的判定'
            }, {
              label: '菱形的判定与性质'
            }, {
              label: '矩形的性质'
            }, {
              label: '矩形的判定'
            }, {
              label: '矩形的判定与性质'
            }, {
              label: '正方形的性质'
            }, {
              label: '正方形的判定'
            }, {
              label: '正方形的判定与性质'
            }, {
              label: '梯形'
            }, {
              label: '直角梯形'
            }, {
              label: '等腰梯形的性质'
            }, {
              label: '等腰梯形的判定'
            }, {
              label: '梯形中位线原理'
            }, {
              label: '*平面向量'
            }, {
              label: '中点四边形'
            }, {
              label: '四边形综合题'
            }, {
              label: '平面向量的加法'
            }, {
              label: '平面向量的减法'
            }]
          }, {
            label: '圆',
            children: [{
              label: '圆的认识'
            }, {
              label: '垂径定理'
            }, {
              label: '垂径定理的应用'
            }, {
              label: '圆心角、弧、弦的关系'
            }, {
              label: '圆周角的定理'
            }, {
              label: '圆内接四边形的性质'
            }, {
              label: '相交弦定理'
            }, {
              label: '点与圆的位置关系'
            }, {
              label: '确定圆的条件'
            }, {
              label: '三角形的外接圆与外心'
            }, {
              label: '直线与圆的位置关系'
            }, {
              label: '切线的性质'
            }, {
              label: '切线的判定'
            }, {
              label: '切线的判定与性质'
            }, {
              label: '弦切角定理'
            }, {
              label: '切弦长定理'
            }, {
              label: '切割线定理'
            }, {
              label: '三角形的内切圆与外心'
            }, {
              label: '圆与圆的位置关系'
            }, {
              label: '相切两圆的性质'
            }, {
              label: '相交两圆的性质'
            }, {
              label: '正多边形和圆'
            }, {
              label: '弧长的计算'
            }, {
              label: '扇形的面积'
            }, {
              label: '圆锥的计算'
            }, {
              label: '圆柱的计算'
            }, {
              label: '圆的综合题'
            }]
          }, {
            label: '尺规作图',
            children: [{
              label: '作图—尺规作图的定义'
            }, {
              label: '作图—基本作图'
            }, {
              label: '作图—复杂作图'
            }, {
              label: '作图—应用与设计作图'
            }, {
              label: '作图—代数计算作图'
            }]
          }, {
            label: '命题与证明',
            children: [{
              label: '命题与定理'
            }, {
              label: '推理与论证'
            }, {
              label: '反证法'
            }, {
              label: '轨迹'
            }]
          }]
        }, {
          label: '图形的变化',
          children: [{
            label: '图形的对称',
            children: [{
              label: '生活中的轴对称现象'
            }, {
              label: '轴对称的性质'
            }, {
              label: '轴对称图形'
            }, {
              label: '镜面对称'
            }, {
              label: '关于x轴、y轴对称的点的坐标'
            }, {
              label: '坐标与图形变化-对称'
            }, {
              label: '作图-轴对称变换'
            }, {
              label: '利用轴对称设计图案'
            }, {
              label: '剪纸问题'
            }, {
              label: '轴对称-最短线路问题'
            }, {
              label: '翻折变换（折叠问题）'
            }, {
              label: '图形的剪拼'
            }]
          }, {
            label: '图形的平移',
            children: [{
              label: '生活中的平移现象'
            }, {
              label: '平移的性质'
            }, {
              label: '坐标与图形变化-平移'
            }, {
              label: '作图-平移变换'
            }, {
              label: '利用平移设计图案'
            }]
          }, {
            label: '图形的旋转',
            children: [{
              label: '生活中的旋转现象'
            }, {
              label: '旋转的性质'
            }, {
              label: '旋转对称图形'
            }, {
              label: '中心对称'
            }, {
              label: '中心对称图形'
            }, {
              label: '关于原点对称的点的坐标'
            }, {
              label: '坐标与图形变化-旋转'
            }, {
              label: '作图-旋转变换'
            }, {
              label: '利用旋转设计图案'
            }, {
              label: '几何变换的类型'
            }, {
              label: '几何变换综合题'
            }]
          }, {
            label: '图形的相似',
            children: [{
              label: '比例的性质'
            }, {
              label: '比例线段'
            }, {
              label: '黄金分割'
            }, {
              label: '平行线分线段成比例'
            }, {
              label: '相似图形'
            }, {
              label: '相似多边形的性质'
            }, {
              label: '相似三角形的性质'
            }, {
              label: '相似三角形的判定'
            }, {
              label: '相似三角形的判定与性质'
            }, {
              label: '相似三角形的应用'
            }, {
              label: '作图-相似变换'
            }, {
              label: '位似变换'
            }, {
              label: '作图-位似变换'
            }, {
              label: '射影定理'
            }, {
              label: '相似形综合题'
            }, {
              label: '实数与向量相乘'
            }, {
              label: '平面向量定理'
            }, {
              label: '向量的线性运算'
            }]
          }, {
            label: '锐角三角形函数',
            children: [{
              label: '锐角三角形函数的定义'
            }, {
              label: '锐角三角形函数的增减性'
            }, {
              label: '同角三角函数的关系'
            }, {
              label: '互余两角三角函数的关系'
            }, {
              label: '特殊角的三角函数值'
            }, {
              label: '计算器—三角函数'
            }, {
              label: '解直角三角形'
            }, {
              label: '解直角三角形的应用'
            }, {
              label: '解直角三角形-坡度坡角问题'
            }, {
              label: '解直角三角形-仰角俯角问题'
            }, {
              label: '解直角三角形-方向角问题'
            }]
          }, {
            label: '投影与视图',
            children: [{
              label: '简单几何体的三视图'
            }, {
              label: '简单组合体的三视图'
            }, {
              label: '由三视图判断几何体'
            }, {
              label: '作图-三视图'
            }, {
              label: '平行投影'
            }, {
              label: '中心投影'
            }, {
              label: '视点、视角和盲区'
            }]
          }]
        }, {
          label: '统计与概率',
          children: [{
            label: '数据收集与处理',
            children: [{
              label: '调查收集数据的过程与方法'
            }, {
              label: '全面调查与抽样调查'
            }, {
              label: '总体、个体、样本、样本容量'
            }, {
              label: '抽样调查的可靠性'
            }, {
              label: '用样本估计总本'
            }, {
              label: '频数与频率'
            }, {
              label: '频数（率）分布表'
            }, {
              label: '频数（率）分布直方图'
            }, {
              label: '频数（率）分布折线图'
            }, {
              label: '统计表'
            }, {
              label: '扇形统计图'
            }, {
              label: '条形统计图'
            }, {
              label: '折线统计图'
            }, {
              label: '统计图的选择'
            }, {
              label: '象形统计图'
            }]
          }, {
            label: '数据分析',
            children: [{
              label: '算术平均数'
            }, {
              label: '加权平均数'
            }, {
              label: '计算器-平均数'
            }, {
              label: '中位数'
            }, {
              label: '众数'
            }, {
              label: '极差'
            }, {
              label: '方差'
            }, {
              label: '标准差'
            }, {
              label: '计算器-标准差与方差'
            }, {
              label: '统计量的选择'
            }]
          }, {
            label: '概率',
            children: [{
              label: '随机事件'
            }, {
              label: '可能性的大小'
            }, {
              label: '概率的意义'
            }, {
              label: '概率公式'
            }, {
              label: '几何概率'
            }, {
              label: '列表法与树状图法'
            }, {
              label: '游戏公平性'
            }, {
              label: '利用频率估算概率'
            }, {
              label: '模拟实验'
            }, {
              label: '待定考点'
            }]
          }]
        }, {
          label: '数学竞赛',
          children: [{
            label: '逻辑推理问题',
            children: [{
              label: '抽屉原理'
            }, {
              label: '排列与组合问题'
            }, {
              label: '加法原理与乘法原理'
            }, {
              label: '容斥原理'
            }, {
              label: '简单的极端原理'
            }, {
              label: '简单的枚举法'
            }, {
              label: '计数方法'
            }, {
              label: '染色问题'
            }]
          }, {
            label: '整数问题',
            children: [{
              label: '数的十进制'
            }, {
              label: '奇数与偶数'
            }, {
              label: '数的整除性'
            }, {
              label: '带余除法'
            }, {
              label: '质数与合数'
            }, {
              label: '约数与倍数'
            }, {
              label: '同余问题'
            }, {
              label: '尾数特征'
            }, {
              label: '完全平方数'
            }, {
              label: '质因数分解'
            }, {
              label: '整数问题的综合运用'
            }]
          }, {
            label: '数与式',
            children: [{
              label: '有理数无理数的概念与运算'
            }, {
              label: '因式定理与综合除法'
            }, {
              label: '余式公理'
            }, {
              label: '立方公式'
            }, {
              label: '整式的等式证明'
            }, {
              label: '对称式和轮换对称式'
            }, {
              label: '部分分式'
            }, {
              label: '分式的条件求值'
            }, {
              label: '分式的等式证明'
            }, {
              label: '拆项、添项、配方、待定系数法'
            }, {
              label: '绝对值'
            }, {
              label: '因式分解'
            }]
          }, {
            label: '方程与不等式',
            children: [{
              label: '含字母系数的一元一次方程'
            }, {
              label: '含绝对值符号的一元一次方程'
            }, {
              label: '二元一次不定方程的整数解'
            }, {
              label: '二元一次不定方程的应用'
            }, {
              label: '二元一次不定方程'
            }, {
              label: '非一次不定方程（组）'
            }, {
              label: '多元一次方程组'
            }, {
              label: '含字母系数的一元二次方程'
            }, {
              label: '含绝对值符号的一元二次方程'
            }, {
              label: '一元二次方程的整数根和有理根'
            }, {
              label: '一元二次方程根的分布'
            }, {
              label: '高次方程'
            }, {
              label: '无理方程'
            }, {
              label: '二元二次方程组'
            }, {
              label: '含字母系数的一元一次方程'
            }, {
              label: '含绝对值的一元一次方程'
            }, {
              label: '一元二次不等式'
            }, {
              label: '应用类问题'
            }]
          }, {
            label: '函数',
            children: [{
              label: 'y=|ax+b|的图象与性质'
            }, {
              label: 'y=|ax2+bx+c|的图象与性质'
            }, {
              label: '含字母系数的二次函数'
            }, {
              label: '整式函数的最值'
            }, {
              label: '分式函数的最值'
            }, {
              label: '绝对值函数的最值'
            }, {
              label: '无理函数的最值'
            }, {
              label: '多元函数的最值'
            }, {
              label: '一元二次方程的最值'
            }, {
              label: '二次函数在给定区间上的最值'
            }, {
              label: '几何问题的最值'
            }, {
              label: '实际问题的最值'
            }, {
              label: '取整函数'
            }, {
              label: '一次函数的最值'
            }, {
              label: '函数最值问题'
            }]
          }, {
            label: '几何',
            children: [{
              label: '三角形边角关系'
            }, {
              label: '面积及等积变换'
            }, {
              label: '三角形的五心'
            }, {
              label: '四点共圆'
            }, {
              label: '圆幂定理'
            }, {
              label: '梅涅劳斯定理与赛瓦定理'
            }, {
              label: '无理函数的最值'
            }, {
              label: '正弦定理与余弦定理'
            }, {
              label: '四种命题及其关系'
            }, {
              label: '一笔画定理'
            }, {
              label: '几何不等式'
            }, {
              label: '立体图形'
            }, {
              label: '路线选择问题'
            }]
          }]
        }],
        defaultProps: {
          children: 'children',
          label: 'label'
        }
      }
    },
    methods: {
      filterNode (value, data) {
        if (!value) return true
        return data.label.indexOf(value) !== -1
      },
      handleNodeClick (data) {
        if (!data.children && this.$store.state.zsdTreeTags.indexOf(data.label) === -1) {
          if (this.$store.state.zsdTreeTags.length < 5) {
            this.$store.state.value = 2
            this.$store.state.zsdTreeTags.push(data.label)
          } else {
            this.$message.warning('最多选择5个知识点')
          }
        }
      }
    },
    computed: {
      zsdTransition () {
        return !(this.zsdTranslate === false || this.$store.state.value === 2)
      }
    },
    watch: {
      zsdText (val) {
        this.$refs.zsdTree.filter(val)
      }
    }
  }
</script>

<style scoped>
  #zsd{
    width: 16%;
    min-width: 200px;
    height: 500px;
    max-height: 500px;
    position: absolute;
    left: 0;
    top: 100px;
    border: 1px solid #E6A23C;
    z-index: 999;
    background-color: #fff;
    overflow-x: visible;
    transition: .5s;
  }
  .movezsd{
    transform: translateX(-100%);
  }
  .arrow{
    color: #fff;
    text-align: center;
    width: 40px;
    height: 100px;
    position: absolute;
    right: -40px;
    top: 200px;
    display: table;
    background-color: #E6A23C;
  }
  .arrow p{
    display: table-cell;
    vertical-align: middle;
  }
  .tree{
    max-height: 500px;
    overflow-y: scroll;
    margin: 0 2px;
  }
  .tree::-webkit-scrollbar {display:none}
</style>
